export default[
    {
        id:1,
        name:"../assets/images/pop.png",
        genre:"POP"
    
    },
    {
        id:2,
        name:"../assets/images/rock.png",
        genre:"ROCK"
    },
    {
        id:3,
        name:"../assets/images/indie.png",
        genre:"INDIE"
    },
    {
        id:4,
        name:"../assets/images/classical.png",
        genre:"CLASSICAL"
    },
    {
        id:5,
        name:"../assets/images/dance.png",
        genre:"DANCE"
    },
    {
        id:6,
        name:"../assets/images/country.png",
        genre:"COUNTRY"
    },
    {
        id:7,
        name:"../assets/images/metal.png",
        genre:"METAL"
    },
    {
        id:8,
        name:"../assets/images/electronic.png",
        genre:"ELECTRONIC"
    },
    {
        id:9,
        name:"../assets/images/jazz.png",
        genre:"JAZZ"
    },
    {
        id:10,
        name:"../assets/images/rap.png",
        genre:"RAP/HIP-HOP"
    },
    {
        id:11,
        name:"../assets/images/reggae.png",
        genre:"REGGAE"
    },
    {
        id:12,
        name:"../assets/images/soul.png",
        genre:"SOUL"
    },
    {
        id:13,
        name:"../assets/images/alternative.png",
        genre:"ALTERNATIVE"
    },
    {
        id:14,
        name:"../assets/images/kpop.png",
        genre:"K-POP"
    },
    {
        id:15,
        name:"../assets/images/urban.png",
        genre:"URBAN"
    }
]