export default[
    {
        id:1,
        name:"Record1",
        album:"Album1",
        artist:"Artist1",
        genre:"Pop"
    },
    {
        id:2,
        name:"Record2",
        album:"Album2",
        artist:"Artist2",
        genre:"Rock"
    },
    {
        id:3,
        name:"Record3",
        album:"Album3",
        artist:"Artist3",
        genre:"Indie"
    },
    {
        id:4,
        name:"Record4",
        album:"Album4",
        artist:"Artist4",
        genre:"Classical"
    },
    {
        id:5,
        name:"Record5",
        album:"Album5",
        artist:"Artist5",
        genre:"Dance"
    },
    {
        id:6,
        name:"Record6",
        album:"Album6",
        artist:"Artist6",
        genre:"Country"
    },
    {
        id:7,
        name:"Record7",
        album:"Album7",
        artist:"Artist7",
        genre:"Heavy Metal"
    },
    {
        id:8,
        name:"Record8",
        album:"Album8",
        artist:"Artist8",
        genre:"Electronic"
    },
    {
        id:9,
        name:"Record9",
        album:"Album9",
        artist:"Artist9",
        genre:"Jazz"
    },
    {
        id:10,
        name:"Record10",
        album:"Album10",
        artist:"Artist10",
        genre:"Rap/Hip-Hop"
    },
    {
        id:11,
        name:"Record11",
        album:"Album11",
        artist:"Artist11",
        genre:"Reggae"
    },
    {
        id:12,
        name:"Record12",
        album:"Album12",
        artist:"Artist12",
        genre:"Soul"
    },
    {
        id:13,
        name:"Record13",
        album:"Album13",
        artist:"Artist13",
        genre:"Alternative"
    },
    {
        id:14,
        name:"Record14",
        album:"Album14",
        artist:"Artist14",
        genre:"K-Pop"
    },
    {
        id:15,
        name:"Record15",
        album:"Album15",
        artist:"Artist15",
        genre:"Urban"
    }
]